name: Daily Scraper

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Python and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install selenium==4.27.1 
        python3 -m pip install pandas==2.0.3

    - name: Install Chrome 
      run: |       
        sudo apt-get update
        sudo apt-get install -y wget curl
        wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.87/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64.zip /usr/local/bin/


    - name: Install ChromeDriver
      run: |   
        sudo apt-get update
        sudo apt-get install -y wget curl 
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.87/linux64/chromedriver-linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/


    - name: Run Scraper
      run: python3 daily_scraper.py

    - name: Commit and Push CSV Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/cumulative_data.csv  # Add your updated CSV file
        git commit -m "Update CSV with new scraped data"
        git push origin main
